spring.jpa.hibernate.ddl-auto=create-drop
# Database Connection Details
# URL for connecting to your MySQL database
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/ecommerce

# Username for database access
spring.datasource.username=root

# Password for database access (consider using a more secure way to store password)
spring.datasource.password=Jockey5@$

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
#dev branch
